---
- name: "Gather host facts"
  setup:
    gather_subset:
      - "network"

- name: "Set Keepalived router_id"
  set_fact:
    keepalived_router_id: "{{ ansible_hostname }}"

- name: "Set Keepalived vrrp_instance_state and priority based on host role"
  set_fact:
    keepalived_vrrp_instance_state: "{{ 'MASTER' if inventory_hostname in groups['master'] else 'BACKUP' }}"
    keepalived_priority: "{{ 150 if inventory_hostname in groups['master'] else 100 }}"

- name: "Set Keepalived unicast_src_ip"
  set_fact:
    keepalived_unicast_src_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: "Set Keepalived unicast_peers"
  set_fact:
    keepalived_unicast_peers: "{{ groups['master'] + groups['backup'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | difference([hostvars[inventory_hostname]['ansible_default_ipv4']['address']]) }}"

- name: "Generate Keepalived hex secret"
  community.general.random_string:
    length: 16
    charset: '0123456789abcdef'
  register: "secret_result"

- name: "Set Keepalived hex secret"
  set_fact:
    keepalived_auth_password: "{{ secret_result.random_string }}"

- name: "Create Keepalived configuration file"
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
  notify: "Restart Keepalived"
