---
- name: "Install Keepalived"
  include_tasks:
    file: "install-keepalived.yml"
  when: "install_keepalived"
- name: "Create Check Script"
  include_tasks:
    file: "create-check-script.yml"
  when: "create_check_script"
- name: "Create Keepalived config"
  include_tasks:
    file: "create-keepalived-config.yml"
  when: "create_keepalived_config"
- name: "Enable Keepalived service"
  include_tasks:
    file: "enable-keepalived-service.yml"
  when: "enable_keepalived_service"
